# Generated by Django 4.2.1 on 2023-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('redhat', 'Redhat\\CentOS'), ('ubuntu', 'Ubuntu'), ('suse', 'Suse'), ('windows', 'Windows')], default='redhat', max_length=64),
        ),
    ]
