# Generated by Django 3.2 on 2023-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_publisher_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': '出版社'},
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '已出版'), ('producing', '待出版')], default='producing', max_length=32),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, help_text='输入地址就行', max_length=50, null=True),
        ),
    ]
